using System;

namespace HotFix
{
	public enum FunctionID
	{
		None,
		MainTab_Shop,
		MainTab_Equip,
		MainTab_Home,
		MainTab_Talent,
		MainTab_Chest,
		Extension = 11,
		Bag,
		Mail,
		Task,
		Ranking,
		Friend,
		Setting,
		BlackMarket,
		ChapterChest = 21,
		IAPShop,
		Sweep,
		MainUI_Guild,
		MainUI_DailyActivities,
		Main_Activity = 31,
		Activity_Ranking,
		Activity_ChallengeTower = 41,
		Main_Activity_CrossArena,
		Main_Activity_DragonsLair,
		Main_Activity_AstralTree,
		Main_Activity_SwordIsland,
		Main_Activity_DeepSeaRuins,
		Pet = 51,
		Collection,
		Mount,
		Artifact,
		Mining,
		RogueDungeon,
		PrivilegeCard = 59,
		RechargeGift,
		PetDeploy1 = 62,
		PetDeploy2,
		PetDeploy3,
		PetTraining,
		AdRefreshSkill = 70,
		NewWorld,
		TalentLegacy,
		ChapterActivityWheel,
		Notice = 80,
		BattleSpeedx2 = 100,
		Activity_Sign,
		Activity_Week,
		Activity_Carnival,
		Activity_TimeGift,
		Activity_ServerOpenGift,
		Activity_SlotTrain,
		Chat_Tab_Show,
		Chat_Server_UnLock,
		Chat_Union_UnLock,
		Chat_Local_UnLock,
		WorldBoss = 114,
		ItemResources,
		TVReward,
		FirstTopUp = 201,
		HangUp,
		ManaCrystalShop,
		PushGift = 301,
		ChainPacks_Halloween = 303,
		ChainPacks_Thanks,
		ChainPacks_Permanent,
		ChainPacks,
		Main_City_Box = 1051,
		Main_City_Shop = 1053
	}
}
