using System;

namespace Server
{
	public enum SkillTriggerType
	{
		RoleRoundFighting,
		BattleStart,
		RoundStart,
		RoundEnd,
		RoleRoundStart,
		RoleRoundEnd,
		RoleHurtHitAfter = 11,
		NormalAttackAfter,
		BigSkillAfter,
		WeaponCritAfter,
		SmallSkillAfter,
		SkillCritAfter,
		RoleOneHurtAfter,
		RoleSkillAfter,
		CustomSkillAfter,
		LegacySkillAfter,
		RoleToThunderHurtAfter = 30,
		RoleToIcicleHurtAfter,
		RoleToKnifeHurtAfter,
		RoleToFireHurtAfter,
		RoleToSwordkeeHurtAfter,
		RoleToFallingSwordHurtAfter,
		KillEnemyAfter = 40,
		NormalAttackKillAfter,
		ComboPointAfter,
		EnemyFreezeAfter,
		HitByHurtedAfter = 50,
		HitByNormalAttackAfter,
		HitByBigSkillAfter,
		CounterAfter,
		MissAfter,
		ComboAfter,
		ShieldAfter,
		HitByHurtedBefore = 60,
		ReviveAfter = 90,
		Thunder = 100,
		Icicle,
		Knife,
		Fire,
		Swordkee,
		FallingSword,
		KnifeTrigger = 112,
		FallingSwordTrigger,
		OnceSkillThunder = 200,
		OnceSkillIcicle,
		OnceSkillKnife,
		OnceSkillFire,
		OnceSkillSwordkee,
		OnceSkillFallingSword,
		RoleCounter,
		ActiveTrigger = 500,
		Undo = 999
	}
}
